"""followers

Revision ID: 93409f86dbae
Revises: d7781033da9c
Create Date: 2022-03-15 21:34:43.481629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93409f86dbae'
down_revision = 'd7781033da9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
