"""users table

Revision ID: b9234534886e
Revises: 
Create Date: 2022-03-12 17:46:38.486918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9234534886e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_contact'), 'user', ['contact'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_contact'), table_name='user')
    op.drop_column('user', 'contact')
    # ### end Alembic commands ###
